---
version: '3.9'
services:
    tradingview-webhook-bot:
        build: TradingView-Webhook-Bot
        container_name: tradingview-webhook-bot
        ports:
            - '80:80'
        restart: unless-stopped